package be.inventj.notemanager.api.authentication;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Created by j.peeters on 13/03/2018.
 */
@DynamoDBTable(tableName = "generated_tokens")
public class Token {

    private String id;
    private String token;

    public Token() {
    }

    public Token(String id, String theOnlyToken) {
        this.id = id;
        this.token = theOnlyToken;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }
}
